#!/bin/bash

date_format=+%d-%b-%Y
time_format=+%H:%M
ext="md"
entries="$(pwd)/entries"
file="${entries}/$(date ${date_format}).${ext}"
editor="vim"

err() {
  echo "ERROR: $@" >&2
  exit 1
}

precheck() {
  readonly REQUIRES=( "${editor}" "gpg" )
  for prog in ${REQUIRES[$@]}; do
    if [[ -z "$(which ${prog})" ]]; then
      err "$prog not installed."
    fi
  done
  if ! [[ -d ${entries} ]]; then
    mkdir ${entries}
  fi
}

new_entry() {
  if [[ -e ${file}.gpg ]]; then
    echo "INFO: ${file}.gpg already exists."
    gpg -d "${file}.gpg" > ${file}
  fi

  printf "\n#%s\n" "$(date ${time_format})" >> "${file}"

  ${editor} "${file}"
  if [[ "$?" -ne 0 ]]; then
    err "Failed to save ${file}"
  fi

  gpg -c "${file}"
  if [[ "$?" -ne 0 ]]; then
    err "Failed to encrypt ${file}"
  fi

  rm ${file}
  if [[ "$?" -ne 0 ]]; then
    err "Failed to delete ${file}"
  fi
}

main(){
  precheck
  new_entry
}
main
